[project]
name = "hands-on-machine-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "al0214", email = "sisang951@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "matplotlib",
    "jupyter",
    "ipykernel",
    "tensorflow",
    "torch",
    "torchvision",
    "xgboost",
    "lightgbm",
    "torchinfo>=1.8.0",
]

[project.scripts]
hands-on-machine-learning = "hands_on_machine_learning:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
